"""add a new label state column for admin reseacher

Revision ID: 066148ade5a6
Revises: 2731d42ed66e
Create Date: 2019-02-13 13:46:11.867397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066148ade5a6'
down_revision = '2731d42ed66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_label_state'), table_name='video')
    op.alter_column('video', 'label_state', existing_nullable=False, new_column_name='label_state_admin', existing_type=sa.Integer())
    op.add_column('video', sa.Column('label_state', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_video_label_state'), 'video', ['label_state'], unique=False)
    op.create_index(op.f('ix_video_label_state_admin'), 'video', ['label_state_admin'], unique=False)
    label_state_column = sa.sql.table('video', sa.sql.column('label_state'))
    op.execute(label_state_column.update().values(**{'label_state': -1}))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_label_state_admin'), table_name='video')
    op.drop_index(op.f('ix_video_label_state'), table_name='video')
    op.drop_column('video', 'label_state')
    op.alter_column('video', 'label_state_admin', existing_nullable=False, new_column_name='label_state', existing_type=sa.Integer())
    op.create_index(op.f('ix_video_label_state'), 'video', ['label_state'], unique=False)
    # ### end Alembic commands ###
