"""add view table and user score

Revision ID: 1ab78a4441c9
Revises: 3df480339533
Create Date: 2019-04-27 16:44:37.523970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab78a4441c9'
down_revision = '3df480339533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('query_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], name=op.f('fk_view_connection_id_connection')),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('fk_view_video_id_video')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_view'))
    )
    op.add_column('batch', sa.Column('user_score', sa.Integer(), nullable=True))
    op.add_column('connection', sa.Column('user_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'user_score')
    op.drop_column('batch', 'user_score')
    op.drop_table('view')
    # ### end Alembic commands ###
