"""init migration

Revision ID: 2731d42ed66e
Revises: 
Create Date: 2019-02-04 12:16:43.685955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2731d42ed66e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_type', sa.Integer(), nullable=False),
    sa.Column('register_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('client_id', name=op.f('uq_user_client_id'))
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('left', sa.Integer(), nullable=False),
    sa.Column('top', sa.Integer(), nullable=False),
    sa.Column('url_part', sa.String(length=768), nullable=False),
    sa.Column('label_state', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video')),
    sa.UniqueConstraint('file_name', name=op.f('uq_video_file_name')),
    sa.UniqueConstraint('url_part', name=op.f('uq_video_url_part'))
    )
    op.create_index(op.f('ix_video_label_state'), 'video', ['label_state'], unique=False)
    op.create_table('connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('client_type', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_connection_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection'))
    )
    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_time', sa.Integer(), nullable=False),
    sa.Column('return_time', sa.Integer(), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], name=op.f('fk_batch_connection_id_connection')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch'))
    )
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], name=op.f('fk_label_batch_id_batch')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_label_user_id_user')),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('fk_label_video_id_video')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label'))
    )
    op.create_index(op.f('ix_label_user_id'), 'label', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_user_id'), table_name='label')
    op.drop_table('label')
    op.drop_table('batch')
    op.drop_table('connection')
    op.drop_index(op.f('ix_video_label_state'), table_name='video')
    op.drop_table('video')
    op.drop_table('user')
    # ### end Alembic commands ###
