"""add the best tutorial action type in the user table

Revision ID: 2d397a316241
Revises: f7c347326521
Create Date: 2019-09-05 18:31:23.937689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d397a316241'
down_revision = 'f7c347326521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('best_tutorial_action', sa.Integer(), nullable=False))
    action_column = sa.sql.table('user', sa.sql.column('best_tutorial_action'))
    op.execute(action_column.update().values(**{'best_tutorial_action': -1}))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'best_tutorial_action')
    # ### end Alembic commands ###
