"""remove score and raw score from the connection table

Revision ID: 38b7b9099636
Revises: 56f15f7e1d7a
Create Date: 2019-08-09 19:11:13.455707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38b7b9099636'
down_revision = '56f15f7e1d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'user_score')
    op.drop_column('connection', 'user_raw_score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('user_raw_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('connection', sa.Column('user_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
