"""add score of user labeling

Revision ID: 3df480339533
Revises: 066148ade5a6
Create Date: 2019-02-15 12:01:09.656353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df480339533'
down_revision = '066148ade5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('num_gold_standard', sa.Integer(), nullable=False))
    op.add_column('batch', sa.Column('num_unlabeled', sa.Integer(), nullable=False))
    op.add_column('batch', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('score', sa.Integer(), nullable=False))
    score_column = sa.sql.table('user', sa.sql.column('score'))
    op.execute(score_column.update().values(**{'score': 0}))
    num_unlabeled_column = sa.sql.table('batch', sa.sql.column('num_unlabeled'))
    op.execute(num_unlabeled_column.update().values(**{'num_unlabeled': 16}))
    num_gold_standard_column = sa.sql.table('batch', sa.sql.column('num_gold_standard'))
    op.execute(num_gold_standard_column.update().values(**{'num_gold_standard': 0}))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'score')
    op.drop_column('batch', 'score')
    op.drop_column('batch', 'num_unlabeled')
    op.drop_column('batch', 'num_gold_standard')
    # ### end Alembic commands ###
