"""add recent updated time of the label to video

Revision ID: 5a5220e7bac1
Revises: 961e45c90596
Create Date: 2019-05-14 16:23:26.060262

"""
from alembic import op
import sqlalchemy as sa
from application import *

# revision identifiers, used by Alembic.
revision = '5a5220e7bac1'
down_revision = '961e45c90596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('label_update_time', sa.Integer(), nullable=True))
    video = sa.sql.table('video', sa.sql.column('id', sa.Integer), sa.sql.column('label_update_time', sa.Integer))
    try:
        t = sa.sql.case(value=video.c.id, whens=((op.inline_literal(b.video_id), op.inline_literal(b.time)) for b in Label.query))
        op.execute(video.update().values(**{'label_update_time': t}))
    except:
        print("Error when computing label_update_time. Maybe the database is empty.")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'label_update_time')
    # ### end Alembic commands ###
