"""add recent updated time of the label to video

Revision ID: 5a5220e7bac1
Revises: 961e45c90596
Create Date: 2019-05-14 16:23:26.060262

"""
from alembic import op
import sqlalchemy as sa
from application import *

# revision identifiers, used by Alembic.
revision = '5a5220e7bac1'
down_revision = '961e45c90596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('label_update_time', sa.Integer(), nullable=True))
    db = op.get_bind()
    video = sa.sql.table('video', sa.sql.column('id', sa.Integer), sa.sql.column('label_update_time', sa.Integer))
    label = sa.sql.table('label', sa.sql.column('id'), sa.sql.column('time'), sa.sql.column('video_id'))
    for b in db.execute(label.select()):
        print("Update label: " + str(b.id))
        db.execute(video.update().where(video.c.id == b.video_id).values(label_update_time=b.time))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'label_update_time')
    # ### end Alembic commands ###
