"""add timestamp for view

Revision ID: 961e45c90596
Revises: 1ab78a4441c9
Create Date: 2019-05-02 14:44:47.791689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961e45c90596'
down_revision = '1ab78a4441c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view', sa.Column('time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('view', 'time')
    # ### end Alembic commands ###
