"""add query_type to the tutorial table

Revision ID: c01ecf16441e
Revises: 2d397a316241
Create Date: 2019-09-06 15:27:37.808885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01ecf16441e'
down_revision = '2d397a316241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutorial', sa.Column('query_type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutorial', 'query_type')
    # ### end Alembic commands ###
